### ISSUE TITLE
ingest fails when BQ table not available

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/piecewise#51]
When running ingest at the beginning of a new month, when the BQ table for the newest month is not yet available, piecewise.ingest fails. The error message received is below. 

Ingest should not fail if the most recent BQ table is not yet available.

```
vagrant@debian-jessie:/opt/piecewise$ sudo python -m piecewise.ingest
Waiting for BigQuery, this could take several minutes.

Took %d s to complete
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/piecewise.git/piecewise/piecewise/ingest.py", line 88, in <module>
    ingest(config)
  File "/opt/piecewise.git/piecewise/piecewise/ingest.py", line 42, in ingest
    query_response = bigquery_service.jobs().getQueryResults(projectId = piecewise.bigquery.PROJECT_NUMBER, jobId = jobId, maxResults = 10000).execute()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/apiclient/http.py", line 723, in execute
    raise HttpError(resp, content, uri=self.uri)
apiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/bigquery/v2/projects/819467010820/queries/job_dd_qMoJekUncI6jLXEgDRPd-j-w?alt=json&maxResults=10000 returned "Not found: Table plx.google:m_lab.2016_02.all">

```

**Comment by critzo** [comment]
This has been resolved.
